services:
  backend:
    build:
      context: ./election-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./election-frontend
      dockerfile: Dockerfile
    environment:
      - XDG_CACHE_HOME=/tmp
      - VITE_CACHE_DIR=/tmp/vite
    ports:
      - "9696:80"
    depends_on:
      - backend
