services:
  backend:
    build:
      context: ./election-backend
    container_name: election-backend
    ports:
      - "9000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build:
      context: ./election-frontend
    container_name: election-frontend
    ports:
      - "9696:80"
    depends_on:
      - backend
