services:
  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:latest
    ports:
      - "9000:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_SECRET_B64=${JWT_SECRET_B64}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always

  frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:latest
    ports:
      - "9696:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://oege.ie.hva.nl:9000
    restart: always

