services:
  backend:
    build:
      context: ./election-backend
      dockerfile: Dockerfile
    ports:
      - "18080:8080"

  frontend:
    build:
      context: ./election-frontend
      dockerfile: Dockerfile

    ports:
      - "19696:80"
    depends_on:
      - backend
