version: "3.9"

services:
  backend:
    build:
      context: ./election-backend
    container_name: election-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build:
      context: ./election-frontend
    container_name: election-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
